### ISSUE TITLE
Multitrack plugin

### ISSUE THREAD

**Issue by AdamGoodApp** [katspaugh/wavesurfer-react#2]
Any way to include Multitracks or even the [Multitrack plugin](https://github.com/katspaugh/wavesurfer-multitrack)?

**Comment by katspaugh** [comment]
Multitrack is bit complicated because it's not an actual wavesurfer plugin, it's more of an app on top of wavesurfer.

**Comment by AdamGoodApp** [comment]
Thank you. I guess its also out of scope to try and get the multiple tracks to play at the same time in this project?

**Comment by katspaugh** [comment]
You could just use wavesurfer-multitrack as is in React, init it in a useEffect, save a reference into a state variable etc. I'm likely not going to create a React-specific wrapper for it in the future.
